### ISSUE TITLE
StringSplitterMapper error delimitier can't be whitespace

### ISSUE THREAD

**Issue by ST2Labs** [wizzie-io/normalizer#40]
Hi, 

I'm running normalizer, but StringSplitterMapper, can't be whitespace its considere like null.

Thanks.

**Comment by ST2Labs** [comment]
This:

< Here is where " " (whitespace) it's considerate like null.-

import static com.cookingfox.guava_preconditions.Preconditions.checkNotNull;

@Override
    public void prepare(Map<String, Object> properties, MetricsManager metricsManager) {
        dimension = checkNotNull((String) properties.get("dimension"), "dimension cannot be null");
        delimiter = checkNotNull((String) properties.get("delimiter"), "delimiter cannot be null");
        fieldNames = checkNotNull((List<String>) properties.get("fields"), "fields cannot be null");
        removeDimension = (boolean) properties.getOrDefault("delete_dimension", false);
    }

**Comment by pablocasares** [comment]
Hello Julian, which version are you using?. 

Please, check this: https://github.com/wizzie-io/normalizer/releases/tag/normalizer-0.7.0
``` 
Update Notes
The io.wizzie.normalizer.funcs.impl.StringSplitterMapper function before use delimitier property, now it has changed to delimiter
``` 

We recommend you to use normalizer 0.7.1. Please, check that your property is called "delimiter".

**Comment by ST2Labs** [comment]
I have using 0.7.3

and correct: name !

>> java.lang.NullPointerException: delimiter cannot be null

**Comment by pablocasares** [comment]
Currently, latest Normalizer version is 0.7.1. 

(you can check that at releases) --> https://github.com/wizzie-io/normalizer/releases. 

I think you mean 0.6.3 branch. In 0.6.3 Normalizer version, delimiter property was called "delimitier" (check this at --> https://github.com/wizzie-io/normalizer/blob/normalizer-0.6.3/functions/src/main/java/io/wizzie/normalizer/funcs/impl/StringSplitterMapper.java#L27 ) so, if you don't want to update to 0.7.1, you should use "delimitier" instead of "delimiter".

**Comment by ST2Labs** [comment]
Thanks, Now Configuration to 0.7.x it correct.

**Comment by pablocasares** [comment]
👍 😄
